query Filters($handle: String!) @blocking @cache(policy: CacheOrNetwork) {
  filters: collection(handle: $handle) {
    products(first: 0) {
      filters {
        id
        label
        type
        values {
          count
          id
          input
          label
        }
      }
    }
  }
}
