query Page($handle: String!) {
  page: metaobject(handle: { handle: $handle, type: "page" }) {
    ...MenuFragment
    content: field(key: "content") {
      value
    }
    children: field(key: "sub_pages") {
      references(first: 10) {
        nodes {
          ... on Metaobject {
            ...MenuFragment
          }
        }
      }
    }
    ...HeroFragment
    ...SectionsFragment
    ...SeoFragment
  }
}
